branches:
  only:
    - master

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"
  
test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"